<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php if ($wo['loggedin']) {
											echo Wo_LoadPage("sidebar/left-sidebar");
										} elseif ($wo['config']['directory_system']) { ?><div class="post_prnt"><?php echo Wo_LoadPage("directory/left-sidebar"); ?></div><?php } ?></div>
		<div class="col-md-7 middlecol">
			<?php if ($wo['config']['user_status'] == 1 && $wo['loggedin']) { ?>
				<div class="wow_content user-status-home wow_home_stories">
					<ul class="status-list">
						<?php if ($wo['config']['can_use_story']) { ?>
							<li class="create_new">
								<a class="avatar" href="<?php echo Wo_SeoLink('index.php?link1=create-status'); ?>" data-ajax="?link1=create-status">
									<img src="<?php echo $wo['user']['avatar']; ?>" alt="<?php echo $wo['user']['name']; ?>">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
										<path fill="currentColor" d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" />
									</svg>
								</a>
								<p title="<?php echo $wo['lang']['create_story'] ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=create-status'); ?>" data-ajax="?link1=create-status"><?php echo $wo['user']['name']; ?></a></p>
							</li>
						<?php } ?>
						<?php
						if ($wo['config']['user_status'] == 1) {
							$get_user_status = Wo_GetFriendsStatus(array('limit' => 4));
							if (!empty($get_user_status)) {
						?>
							<?php
								foreach ($get_user_status as $key => $wo['user_status']) {
									echo Wo_LoadPage('home/user-status');
								}
							}
							?>
						<?php } ?>
						<?php if (!empty($get_user_status) && count($get_user_status) > 3) { ?>
							<li class="view-more-stories">
								<a class="avatar" href="<?php echo Wo_SeoLink('index.php?link1=more-status'); ?>">
									<div><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
											<path fill="currentColor" d="M21.47,4.35L20.13,3.79V12.82L22.56,6.96C22.97,5.94 22.5,4.77 21.47,4.35M1.97,8.05L6.93,20C7.24,20.77 7.97,21.24 8.74,21.26C9,21.26 9.27,21.21 9.53,21.1L16.9,18.05C17.65,17.74 18.11,17 18.13,16.26C18.14,16 18.09,15.71 18,15.45L13,3.5C12.71,2.73 11.97,2.26 11.19,2.25C10.93,2.25 10.67,2.31 10.42,2.4L3.06,5.45C2.04,5.87 1.55,7.04 1.97,8.05M18.12,4.25A2,2 0 0,0 16.12,2.25H14.67L18.12,10.59" />
										</svg></div>
								</a>
								<p><a href="<?php echo Wo_SeoLink('index.php?link1=more-status'); ?>"><?php echo $wo['lang']['see_all'] ?></a></p>
							</li>
						<?php } ?>
					</ul>
				</div>
			<?php
			}
			if (Wo_IsThereAnnouncement() === true) {
				$announcement = Wo_GetHomeAnnouncements();
			?>
				<div class="home-announcement">
					<div class="alert wow_content">
						<span class="close announcements-option" data-toggle="tooltip" onclick="Wo_ViewAnnouncement(<?php echo $announcement['id']; ?>);" title="<?php echo $wo['lang']['hide']; ?>">
							<i class="fa fa-remove"></i>
						</span>
						<?php echo $announcement['text']; ?>
					</div>
				</div>
				<!-- .home-announcement -->
			<?php
			}
			if ($wo['loggedin'] == true) {
				echo Wo_LoadPage('story/publisher-box');
			}
			?>

			<?php if (Wo_IsMobile() == true) { ?>
				<?php if ($wo['config']['order_posts_by'] == 0) { ?>
					<div class="wow_content order-by">
						<div class="dropdown">
							<?php echo $wo['lang']['store_posts_by'] ?>: <a class="dropdown-toggle" type="button" data-toggle="dropdown">
								<span class="order-text"><?php echo ($wo['user']['order_posts_by'] == 0) ? $wo['lang']['all'] : $wo['lang']['people_i_follow']; ?></span>
								<span class="caret"></span></a>
							<ul class="dropdown-menu post_order_feed">
								<li>
									<a href="javascript:void(0);" onclick="Wo_StorePosts(0);">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
											<path fill="currentColor" d="M2 14H8V20H2M16 8H10V10H16M2 10H8V4H2M10 4V6H22V4M10 20H16V18H10M10 16H22V14H10"></path>
										</svg>
										&nbsp;&nbsp;&nbsp;
										<div>
											<b><?php echo $wo['lang']['all'] ?></b>
											<p><?php echo $wo['lang']['all_tx'] ?></p>
										</div>
									</a>
								</li>
								<li>
									<a href="javascript:void(0);" onclick="Wo_StorePosts(1);">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
											<path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z"></path>
										</svg>
										&nbsp;&nbsp;&nbsp;
										<div>
											<b><?php echo $wo['lang']['people_i_follow'] ?></b>
											<p><?php echo $wo['lang']['people_i_follow_tx'] ?></p>
										</div>
									</a>
								</li>
							</ul>
						</div>
					</div>
				<?php } ?>
			<?php } ?>

			<?php if ($wo['config']['afternoon_system'] == 1) { ?>
				<div class="alert alert-dismissible greetalert hidden" role="alert">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="setCookie('day_status', '1', 3);">
						<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
							<path stroke="none" d="M0 0h24v24H0z" fill="none" />
							<path d="M18 6l-12 12" />
							<path d="M6 6l12 12" />
						</svg>
					</button>
					<div id="daynightmsg"></div>
				</div>
			<?php } ?>

			<?php if ($wo['page'] == 'home' && in_array($wo['config']['website_mode'], array('facebook', 'linkedin'))) { ?>
				<div id="scroll_filter_click"></div>
				<ul class="list-group filterby" id="filterby-post">
					<li class="list-group-item hidden" contenteditable="false">Filter by</li>
					<li class="list-group-item avtive filter-by-li filter_negative_clr" onclick="Wo_FilterPostBy('all');" dir="auto">
						<svg xmlns="http://www.w3.org/2000/svg" width="18" height="19" viewBox="0 0 18 19" fill="none">
							<path fill-rule="evenodd" clip-rule="evenodd" d="M1.47651 3.47627C1.88057 3.07221 2.42858 2.84521 3 2.84521H8.25C8.6115 2.84521 8.90455 3.13826 8.90455 3.49976C8.90455 3.86126 8.6115 4.15431 8.25 4.15431H3C2.77578 4.15431 2.56073 4.24338 2.40218 4.40193C2.24362 4.56049 2.15455 4.77553 2.15455 4.99976V15.4998C2.15455 15.724 2.24362 15.939 2.40218 16.0976C2.56073 16.2561 2.77578 16.3452 3 16.3452H13.5C13.7242 16.3452 13.9393 16.2561 14.0978 16.0976C14.2564 15.939 14.3455 15.724 14.3455 15.4998V10.2498C14.3455 9.88827 14.6385 9.59521 15 9.59521C15.3615 9.59521 15.6546 9.88827 15.6546 10.2498V15.4998C15.6546 16.0712 15.4276 16.6192 15.0235 17.0233C14.6194 17.4273 14.0714 17.6543 13.5 17.6543H3C2.42858 17.6543 1.88057 17.4273 1.47651 17.0233C1.07246 16.6192 0.845459 16.0712 0.845459 15.4998V4.99976C0.845459 4.42834 1.07245 3.88032 1.47651 3.47627Z" fill="#267EDE" />
							<path fill-rule="evenodd" clip-rule="evenodd" d="M15 2.56349C14.7517 2.56349 14.5135 2.66215 14.3379 2.83776L7.34105 9.83457L6.89961 11.6003L8.66538 11.1589L15.6622 4.1621C15.8378 3.98648 15.9365 3.74829 15.9365 3.49993C15.9365 3.25157 15.8378 3.01338 15.6622 2.83776C15.4866 2.66215 15.2484 2.56349 15 2.56349ZM13.4122 1.9121C13.8333 1.49098 14.4045 1.25439 15 1.25439C15.5956 1.25439 16.1667 1.49098 16.5879 1.9121C17.009 2.33322 17.2456 2.90438 17.2456 3.49993C17.2456 4.09548 17.009 4.66664 16.5879 5.08776L9.46285 12.2128C9.37897 12.2966 9.27386 12.3562 9.15877 12.3849L6.15877 13.1349C5.93572 13.1907 5.69976 13.1253 5.53718 12.9628C5.37461 12.8002 5.30925 12.5642 5.36502 12.3412L6.11502 9.34118C6.14379 9.22609 6.2033 9.12098 6.28718 9.0371L13.4122 1.9121Z" fill="#267EDE" />
						</svg>
						Все записи
					</li>
					<li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('text');" dir="auto">
						<svg xmlns="http://www.w3.org/2000/svg" width="18" height="19" viewBox="0 0 18 19" fill="none">
							<path fill-rule="evenodd" clip-rule="evenodd" d="M14.7272 2.62745H3.27266C2.64004 2.62745 2.12721 3.14029 2.12721 3.7729V15.2275C2.12721 15.8601 2.64004 16.3729 3.27266 16.3729H14.7272C15.3598 16.3729 15.8727 15.8601 15.8727 15.2275V3.77291C15.8727 3.14029 15.3598 2.62745 14.7272 2.62745ZM3.27266 1.31836C1.91705 1.31836 0.818115 2.4173 0.818115 3.7729V15.2275C0.818115 16.5831 1.91705 17.682 3.27266 17.682H14.7272C16.0828 17.682 17.1818 16.5831 17.1818 15.2275V3.77291C17.1818 2.4173 16.0828 1.31836 14.7272 1.31836H3.27266Z" fill="#999999" />
							<path fill-rule="evenodd" clip-rule="evenodd" d="M4.1582 6.18726C4.1582 5.82576 4.45125 5.53271 4.81275 5.53271L10.1867 5.53272C10.5482 5.53272 10.8412 5.82577 10.8412 6.18726C10.8412 6.54876 10.5482 6.84181 10.1867 6.84181L4.81275 6.84181C4.45125 6.84181 4.1582 6.54876 4.1582 6.18726Z" fill="#999999" />
							<path fill-rule="evenodd" clip-rule="evenodd" d="M4.1582 9.78785C4.1582 9.42635 4.45125 9.1333 4.81275 9.1333L13.1867 9.1333C13.5482 9.1333 13.8412 9.42635 13.8412 9.78785C13.8412 10.1493 13.5482 10.4424 13.1867 10.4424L4.81275 10.4424C4.45125 10.4424 4.1582 10.1493 4.1582 9.78785Z" fill="#999999" />
							<path fill-rule="evenodd" clip-rule="evenodd" d="M4.1582 13.3875C4.1582 13.026 4.45125 12.7329 4.81275 12.7329L7.78667 12.7329C8.14817 12.7329 8.44122 13.026 8.44122 13.3875C8.44122 13.749 8.14817 14.042 7.78667 14.042L4.81275 14.042C4.45125 14.042 4.1582 13.749 4.1582 13.3875Z" fill="#999999" />
						</svg>
						Статьи
					</li>
					<li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('photos');" dir="auto">
						<svg xmlns="http://www.w3.org/2000/svg" width="18" height="19" viewBox="0 0 18 19" fill="none">
							<g clip-path="url(#clip0_706_916)">
								<path d="M2.0142 17.9544H15.9856C17.0571 17.9544 17.9142 17.0972 17.9142 16.0258L17.914 2.77904C17.914 1.70761 17.0569 0.850472 15.9854 0.850472H2.01402C0.942592 0.850472 0.0854492 1.70761 0.0854492 2.77904L0.0856334 16.0258C0.0856334 17.0972 0.942776 17.9544 2.0142 17.9544ZM1.37135 16.0258V12.9401L6.98563 9.2758L14.0142 16.6687H2.0142C1.64992 16.6687 1.37135 16.3901 1.37135 16.0258ZM15.9856 16.6687H15.7928L10.8428 11.4615L13.0928 9.31865L16.6285 12.7258V16.0258C16.6285 16.3901 16.3499 16.6687 15.9856 16.6687ZM2.01402 2.13619H15.9854C16.3497 2.13619 16.6283 2.41476 16.6283 2.77904L16.6285 10.9472L13.5428 7.99008C13.2856 7.75437 12.8999 7.75437 12.6642 7.99008L9.94278 10.5401L7.54278 8.01151C7.32849 7.79722 6.98563 7.75437 6.72849 7.9258L1.37135 11.4187L1.37116 2.77904C1.37116 2.41476 1.64973 2.13619 2.01402 2.13619Z" fill="#999999" />
								<circle cx="4.49998" cy="5.00022" r="1.22727" fill="#999999" />
							</g>
							<defs>
								<clipPath id="clip0_706_916">
									<rect width="18" height="18" fill="white" transform="translate(0 0.5)" />
								</clipPath>
							</defs>
						</svg>
						Фото
					</li>
					<li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('video');" dir="auto">
						<svg xmlns="http://www.w3.org/2000/svg" width="18" height="19" viewBox="0 0 18 19" fill="none">
							<g clip-path="url(#clip0_706_919)">
								<path d="M12.8137 8.72913L6.76905 5.70953C6.5744 5.61241 6.34333 5.62267 6.15831 5.73716C5.97328 5.85165 5.86047 6.05362 5.86047 6.27109V12.3105C5.86047 12.5282 5.97308 12.7302 6.1581 12.8446C6.25898 12.9072 6.37347 12.9384 6.48838 12.9384C6.58424 12.9384 6.68031 12.9166 6.76905 12.8725L12.8137 9.85267C13.0264 9.74634 13.1607 9.52888 13.1607 9.2909C13.1607 9.05293 13.0261 8.83546 12.8137 8.72913ZM7.11628 11.295V7.28683L11.1278 9.2909L7.11628 11.295ZM9.00001 0.526367C4.12389 0.526367 0.156982 4.49327 0.156982 9.36939C0.156982 14.2455 4.12389 18.2124 9.00001 18.2124C13.8761 18.2124 17.843 14.2455 17.843 9.36939C17.843 4.49327 13.8761 0.526367 9.00001 0.526367ZM9.00001 16.9566C4.81647 16.9566 1.4128 13.5529 1.4128 9.36939C1.4128 5.18586 4.81647 1.78218 9.00001 1.78218C13.1835 1.78218 16.5872 5.18586 16.5872 9.36939C16.5872 13.5529 13.1835 16.9566 9.00001 16.9566Z" fill="#999999" />
							</g>
							<defs>
								<clipPath id="clip0_706_919">
									<rect width="18" height="18" fill="white" transform="translate(0 0.5)" />
								</clipPath>
							</defs>
						</svg>
						Видео
					</li>
					<li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('music');" dir="auto">
						<svg xmlns="http://www.w3.org/2000/svg" width="18" height="19" viewBox="0 0 18 19" fill="none">
							<g clip-path="url(#clip0_706_922)">
								<path fill-rule="evenodd" clip-rule="evenodd" d="M11.3727 9.09091V4.18182C11.3727 2.8714 10.3104 1.80909 8.99994 1.80909C7.68951 1.80909 6.62721 2.8714 6.62721 4.18182V9.09091C6.62721 10.4013 7.68951 11.4636 8.99994 11.4636C10.3104 11.4636 11.3727 10.4013 11.3727 9.09091ZM8.99994 0.5C6.96652 0.5 5.31812 2.14841 5.31812 4.18182V9.09091C5.31812 11.1243 6.96652 12.7727 8.99994 12.7727C11.0333 12.7727 12.6818 11.1243 12.6818 9.09091V4.18182C12.6818 2.14841 11.0333 0.5 8.99994 0.5Z" fill="#999999" />
								<path fill-rule="evenodd" clip-rule="evenodd" d="M3.27295 8.02734C3.63445 8.02734 3.9275 8.32039 3.9275 8.68189C3.9275 11.4835 6.19864 13.7546 9.00023 13.7546C11.8018 13.7546 14.073 11.4835 14.073 8.68189C14.073 8.32039 14.366 8.02734 14.7275 8.02734C15.089 8.02734 15.382 8.32039 15.382 8.68189C15.382 12.2065 12.5248 15.0637 9.00023 15.0637C5.47565 15.0637 2.61841 12.2065 2.61841 8.68189C2.61841 8.32039 2.91146 8.02734 3.27295 8.02734Z" fill="#999999" />
								<path fill-rule="evenodd" clip-rule="evenodd" d="M8.20029 17.8455V14.5728H9.80029V17.8455H8.20029Z" fill="#999999" />
								<path fill-rule="evenodd" clip-rule="evenodd" d="M5.073 17.8455C5.073 17.484 5.36605 17.1909 5.72754 17.1909H11.8639C12.2254 17.1909 12.5185 17.484 12.5185 17.8455C12.5185 18.207 12.2254 18.5 11.8639 18.5H5.72754C5.36605 18.5 5.073 18.207 5.073 17.8455Z" fill="#999999" />
							</g>
							<defs>
								<clipPath id="clip0_706_922">
									<rect width="18" height="18" fill="white" transform="translate(0 0.5)" />
								</clipPath>
							</defs>
						</svg>
						Аудио
					</li>
					<?php if ($wo['config']['fileSharing'] == 1) { ?>
						<li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('files');" dir="auto">
							<svg xmlns="http://www.w3.org/2000/svg" width="18" height="19" viewBox="0 0 18 19" fill="none">
								<g clip-path="url(#clip0_706_925)">
									<path fill-rule="evenodd" clip-rule="evenodd" d="M4.09102 17.1909H13.9092C14.5418 17.1909 15.0547 16.6781 15.0547 16.0455V6.33002L10.8815 1.80909H4.09102C3.4584 1.80909 2.94557 2.32193 2.94557 2.95455V16.0455C2.94557 16.6781 3.4584 17.1909 4.09102 17.1909ZM4.09102 0.5C2.73541 0.5 1.63647 1.59894 1.63647 2.95455V16.0455C1.63647 17.4011 2.73541 18.5 4.09102 18.5H13.9092C15.2648 18.5 16.3637 17.4011 16.3637 16.0455V6.13808C16.3637 5.93239 16.2863 5.73426 16.1468 5.58312L11.6976 0.763225C11.5427 0.595431 11.3248 0.5 11.0964 0.5H4.09102Z" fill="#999999" />
									<path fill-rule="evenodd" clip-rule="evenodd" d="M9.98193 3.77282V0.90918H11.291V3.77282C11.291 4.76693 12.0969 5.57282 13.091 5.57282H15.9547V6.88191H13.091C11.3739 6.88191 9.98193 5.48992 9.98193 3.77282Z" fill="#999999" />
								</g>
								<defs>
									<clipPath id="clip0_706_925">
										<rect width="18" height="18" fill="white" transform="translate(0 0.5)" />
									</clipPath>
								</defs>
							</svg>
							Файлы
						</li>
					<?php } ?>
					<?php //if ($wo['config']['google_map'] == 1 || $wo['config']['yandex_map'] == 1) { 
					?>
					<!-- <li class="list-group-item filter-by-li" onclick="Wo_FilterPostBy('maps');" dir="auto">
							<svg width="18" height="20" viewBox="0 0 18 20" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M17 9.17548C17 13.6907 13.4183 19 9 19C4.58172 19 1 13.6907 1 9.17548C1 4.66029 4.58172 1 9 1C13.4183 1 17 4.66029 17 9.17548Z" stroke="currentColor" stroke-width="1.5" />
								<path d="M6.5 8.5C6.5 7.11929 7.61929 6 9 6C10.3807 6 11.5 7.11929 11.5 8.5C11.5 9.88071 10.3807 11 9 11C7.61929 11 6.5 9.88071 6.5 8.5Z" class="icon_main" stroke-width="1.5" />
							</svg>
						</li> -->
					<?php //} 
					?>
				</ul>
			<?php } ?>

			<div class="btn btn-main btn-active posts-count" onclick="Wo_GetNewPosts();"></div>
			<div class="posts_load">
				<div id="posts-laoded">
					<div class="wo_loading_post">
						<div class="wo_post_skel_head">
							<div class="skel skel_avatar"></div>
							<div>
								<div class="skel skel_noti_name"></div>
								<div class="skel skel_noti_time"></div>
							</div>
						</div>
						<div class="wo_post_skel_body">
							<div class="skel skel_desc"></div>
							<div class="skel skel_desc"></div>
							<div class="skel skel_desc"></div>
						</div>
						<div class="wo_post_skel_foot">
							<div class="skel skel_action"></div>
							<div class="skel skel_action"></div>
							<div class="skel skel_action"></div>
						</div>
					</div>
					<div class="wo_loading_post">
						<div class="wo_post_skel_head">
							<div class="skel skel_avatar"></div>
							<div>
								<div class="skel skel_noti_name"></div>
								<div class="skel skel_noti_time"></div>
							</div>
						</div>
						<div class="wo_post_skel_body">
							<div class="skel skel_desc"></div>
							<div class="skel skel_desc"></div>
							<div class="skel skel_desc"></div>
						</div>
						<div class="wo_post_skel_foot">
							<div class="skel skel_action"></div>
							<div class="skel skel_action"></div>
							<div class="skel skel_action"></div>
						</div>
					</div>
				</div>
			</div>
			<!-- #posts -->
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content'); ?>
	</div>
</div>
<!-- .page-margin -->

<?php
if ($wo['loggedin'] && $wo['user']['social_login'] == 1) {
	echo Wo_LoadPage('modals/create-password');
}
?>

<script type="text/javascript">
	$(function() {
		loadposts();
	});


	// $(document).on('click', '.story-image-wrapper', function(event) {
	//   event.preventDefault();
	//   $value = $(this).parents(".story-container").attr('data-status-id');
	//   $.post(Wo_Ajax_Requests_File() + '?f=story_view', {id: $value}, function(data, textStatus, xhr) {

	//   });
	// });

	/* Standard syntax */
	document.addEventListener("fullscreenchange", function() {
		$('video').toggleClass('active-player');
	});

	/* Firefox */
	document.addEventListener("mozfullscreenchange", function() {
		$('video').toggleClass('active-player');
	});

	/* Chrome, Safari and Opera */
	document.addEventListener("webkitfullscreenchange", function() {
		$('video').toggleClass('active-player');
	});

	/* IE / Edge */
	document.addEventListener("msfullscreenchange", function() {
		$('video').toggleClass('active-player');
	});


	function loadposts() {
		$("#posts-laoded").load(Wo_Ajax_Requests_File() + '?f=load_posts', function enter() {
			Wo_FinishBar();
			window.fbAsyncInit = function() {
				FB.init({
					appId: '374255706379985',
					xfbml: true,
					version: 'v3.2'
				});
			};
			$(".post-description p, .product-description").each(function(index, el) {
				ReadMoreText(this);
			});
			$(".post-commet-textarea .textarea").triggeredAutocomplete({
				hidden: '#hidden_inputbox_comment',
				source: Wo_Ajax_Requests_File() + "?f=mention",
				trigger: "@"
			});
			$(".comment-reply textarea").triggeredAutocomplete({
				hidden: '#hidden_inputbox_comment_reply',
				source: Wo_Ajax_Requests_File() + "?f=mention",
				trigger: "@"
			});
			$('#load-more-posts').show();

		});
	}
	<?php if ($wo['loggedin'] && $wo['user']['social_login'] == 1) { ?>
		$(window).on("load", function(e) {
			$('#create-password').modal('show');
		});
		$(function() {
			var create_password_container = $('#create-password');
			$('form.create-password').ajaxForm({
				url: Wo_Ajax_Requests_File() + '?f=update_new_logged_user_details',
				beforeSend: function() {
					Wo_progressIconLoader($('form.create-password').find('button'));
				},
				success: function(data) {
					if (data.status == 200) {
						create_password_container.find('.error-container').html("<div class='alert alert-success'>" + data.message + "</div>");
						$('#update-username').attr('href', data.url);
						setTimeout(function() {
							$('#create-password').modal('hide');
						}, 1500);
					} else {
						var errors = data.errors.join("<br>");
						create_password_container.find('.error-container').html("<div class='alert alert-danger'>" + errors + "</div>");
					}
					Wo_progressIconLoader($('form.create-password').find('button'));
				}
			});
		});

	<?php } ?>

	<?php if (Wo_IsMobile() == true) { ?>

		function Wo_StorePosts(type) {
			if (type > 1) {
				return false;
			}
			if (type == 0) {
				$('.order-text').text('<?php echo $wo['lang']['all'] ?>');
			} else {
				$('.order-text').text('<?php echo $wo['lang']['people_i_follow'] ?>');
			}
			$('#posts-laoded').html('<div class="wo_loading_post"><div class="wo_loading_post_child"></div></div>');
			$.get(Wo_Ajax_Requests_File() + '?f=update_order_by', {
				type: type
			}, function(data) {
				if (data.status == 200) {
					loadposts();
				}
			});
		}
	<?php } ?>

	function Wo_ViewAnnouncement(id) {
		var announcement_container = $('.home-announcement');
		$.get(Wo_Ajax_Requests_File() + '?f=update_announcement_views', {
			id: id
		}, function(data) {
			if (data.status == 200) {
				announcement_container.slideUp(200, function() {
					$(this).remove();
				});
			}
		});
	}

	function setCookie(cname, cvalue, exdays) {
		var d = new Date();
		d.setTime(d.getTime() + (exdays * 60 * 60 * 1000));
		var expires = "expires=" + d;
		document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
	}

	function getCookieValue(a) {
		var b = document.cookie.match('(^|;)\\s*' + a + '\\s*=\\s*([^;]+)');
		return b ? b.pop() : '';
	}
	<?php if ($wo['loggedin']) { ?>
		$(function() {
			var is_day_enabled = getCookieValue('day_status');
			var myDate = new Date();
			var hrs = myDate.getHours();
			var greet;
			var color;
			var quote;
			if (hrs < 12) {
				greet = "<?php echo $wo['lang']['good_morning'] ?>" + ', <?php echo $wo['user']['name'] ?> <img src="<?php echo $wo['config']['theme_url']; ?>/img/park.png"/>';
				color = '#7FC583';
				quote = "<?php echo $wo['lang']['good_morning_quote'] ?>";
			} else if (hrs >= 12 && hrs <= 18) {
				greet = "<?php echo $wo['lang']['good_afternoon'] ?>" + ', <?php echo $wo['user']['name'] ?> <img src="<?php echo $wo['config']['theme_url']; ?>/img/desert.png"/>';
				color = '#ffc107';
				quote = "<?php echo $wo['lang']['good_afternoon_quote'] ?>";
			} else if (hrs >= 18 && hrs <= 24) {
				greet = "<?php echo $wo['lang']['good_evening'] ?>" + ', <?php echo $wo['user']['name'] ?> <img src="<?php echo $wo['config']['theme_url']; ?>/img/sea.png"/>';
				color = '#FF4F70';
				quote = "<?php echo $wo['lang']['good_evening_quote'] ?>";
			}
			if (is_day_enabled != 1) {
				setTimeout(function() {
					$('.greetalert').css('border-color', color);
					$('#daynightmsg').html('<div class="small-texts">' + greet + '</div><p>' + quote + '</p>');
					$('.greetalert').removeClass('hidden');
				}, 100);
			}
		});
	<?php } ?>
</script>