<?php
if (Wo_IsAdmin()) {
    header('Location: ' . $wo['config']['site_url'] . '/admincp/verifications_requests');
    exit();
}

$ver = Get_VerificationDoc();
//var_dump($wo['user']['id']);
//var_dump($wo['user']['verified']);
//var_dump(Wo_GetMedia($ver->passport));
?>

<div class="page-margin mt-0">
    <div class="wow_content popular_posts_hdr">
        <h2><svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M6.51721 12.0498L5.56148 15.8055C5.27453 16.9332 6.48077 17.8703 7.55507 17.3543L9.16574 16.5808C9.69148 16.3283 10.3088 16.3283 10.8346 16.5808L12.4452 17.3543C13.5196 17.8703 14.7258 16.9332 14.4388 15.8055L13.4831 12.0498" class="icon_main" stroke-width="1.5" />
                <path d="M4.79539 5.96852C5.18749 4.34956 6.49269 3.08545 8.16429 2.70569C9.37149 2.43144 10.6279 2.43144 11.8351 2.70569C13.5067 3.08545 14.8119 4.34956 15.204 5.96853C15.4871 7.13773 15.4871 8.35453 15.204 9.52373C14.8119 11.1427 13.5067 12.4068 11.8351 12.7866C10.6279 13.0608 9.3715 13.0608 8.16429 12.7866C6.49269 12.4068 5.18749 11.1427 4.79539 9.52373C4.51221 8.35453 4.51221 7.13773 4.79539 5.96852Z" stroke="currentColor" stroke-width="1.5" />
            </svg>&nbsp;<?php echo $wo['lang']['profile_verification']; ?></h2>
    </div>
</div>

<div class="wo_settings_page wow_content">

    <?php if (!empty($wo['available_verified_features'])) { ?>
        <div>
            <h5><?php echo $wo['lang']['after_verified'] ?></h5>
            <ol>
                <?php foreach ($wo['available_verified_features'] as $key => $value) { ?>
                    <li><?php echo $wo['lang'][$value]; ?></li>
                <?php } ?>
            </ol>
        </div>
    <?php } ?>


    <?php if (Wo_IsVerificationRequestExists() && $ver && !empty($ver->passport)) : ?>
        <div class="verification-status">
            <h4>
                <p><a class="btn btn-main btn-mat" href="<?php echo Wo_GetMedia(Get_VerificationDoc()->passport); ?>">ПОСМОТРЕТЬ ДОКУМЕНТ С ПОДПИСЬЮ</a></p>
                <p><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-check">
                        <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                        <circle cx="8.5" cy="7" r="4"></circle>
                        <polyline points="17 11 19 13 23 9"></polyline>
                    </svg> &nbsp;
                    <?php echo $wo['lang']['verification_sent']; ?> </p>

            </h4>
        </div>
    <?php elseif ($wo['user']['verified'] == 1) : ?>
        <div class="verification-status">
            <h4>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="verified-color feather feather-check-circle">
                    <path d="M23,12L20.56,9.22L20.9,5.54L17.29,4.72L15.4,1.54L12,3L8.6,1.54L6.71,4.72L3.1,5.53L3.44,9.21L1,12L3.44,14.78L3.1,18.47L6.71,19.29L8.6,22.47L12,21L15.4,22.46L17.29,19.28L20.9,18.46L20.56,14.78L23,12M10,17L6,13L7.41,11.59L10,14.17L16.59,7.58L18,9L10,17Z"></path>
                </svg>
                <?php echo $wo['lang']['verification_complete']; ?>
            </h4>
        </div>
    <?php else : ?>
        <form action="#" method="post" class="form-horizontal setting-verification-form">
            <div id="verificate-user-alert"></div>
            <div class="wow_form_fields">
                <!-- <label for="event-name">Тип</label> -->
                <div class="wow_srch_innr_filtr">
                    <div class="pp_mat_input">
                        <div class="round_check">
                            <input type="radio" name="type_ver" id="type_ver-0" value="0" <?php echo ($ver && $ver->type_ver == '0') ? 'checked' : ''; ?>>
                                <label class="radio-inline" for="type_ver-0">ИП</label>
                        </div>
                        <div class="round_check">
                            <input type="radio" name="type_ver" id="type_ver-1" value="1" <?php echo ($ver && $ver->type_ver == '1') ? 'checked' : ''; ?>>
                                <label class="radio-inline" for="type_ver-1">ЮР. ЛИЦО</label>
                        </div>
                        <div class="round_check">
                            <input type="radio" name="type_ver" id="type_ver-2" value="2" <?php echo ($ver && $ver->type_ver == '2') ? 'checked' : ''; ?>>
                                <label class="radio-inline" for="type_ver-2">Самозанятый</label>
                        </div>

                    </div>
                </div>
            </div>
            <div id="typeform-0" style="">
                <h4>САМОЗАНЯТЫЙ / ИП</h4>
                <div class="wow_form_fields">
                    <label for="fio">ФИО *</label>
                    <input id="fio" name="fio" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->fio : ''; ?>">
                </div>
                <div class="wow_form_fields ogrn_fields">
                    <label for="ogrnip">ОГРНИП *</label>
                    <input id="ogrnip" name="ogrnip" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->ogrnip : ''; ?>">
                </div>
            </div>

            <div id="typeform-1" style="display: none">
                <h4>ЮР. ЛИЦО</h4>
                <div class="wow_form_fields">
                    <label for="org">Наименование организации *</label>
                    <input id="org" name="org" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->org : ''; ?>">
                </div>
                <div class="wow_form_fields">
                    <label for="ogrn">ОГРН *</label>
                    <input id="ogrn" name="ogrn" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->ogrn : ''; ?>">
                </div>
            </div>   
            <div id="all_fields" style="">
                <div class="wow_form_fields">
                    <label for="inn">ИНН</label>
                    <input id="inn" name="inn" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->inn : ''; ?>">
                </div>
                <div class="wow_form_fields">
                    <label for="bank">Наименование банка</label>
                    <input id="bank" name="bank" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->bank : ''; ?>">
                </div>
                <div class="wow_form_fields">
                    <label for="bik">БИК</label>
                    <input id="bik" name="bik" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->bik : ''; ?>">
                </div>
                <div class="wow_form_fields">
                    <label for="rs">Р/С</label>
                    <input id="rs" name="rs" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->rs : ''; ?>">
                </div>
                <div class="wow_form_fields">
                    <label for="kor">Кор. счет</label>
                    <input id="kor" name="kor" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->kor : ''; ?>">
                </div>
                <div class="wow_form_fields">
                    <label for="address">Адрес <span id="address_type"></span></label>
                    <input id="adress" name="address" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->address : ''; ?>">
                </div>
                <div class="wow_form_fields">
                    <label for="tel">Телефон</label>
                    <input id="tel" name="tel" type="text" class="form-control input-md" value="<?php echo ($ver) ? $ver->tel : ''; ?>">
                </div>
                <div class="wow_form_fields">
                    <label for="email">Почта</label>
                    <input id="email" name="email" type="email" class="form-control input-md" value="<?php echo ($ver) ? $ver->email : $wo['user']['email']; ?>">
                </div>
            </div>
            <div class="wow_form_fields mb-0">
                <label for="text"><?php echo $wo['lang']['upload_docs']; ?></label>
                <span class="help-block"><?php echo $wo['lang']['select_verif_images']; ?></span>
            </div>

            <div class="select-user-verification-data">
                <div class="select-user-verification-photos">
                    <div class="pull-left text-center" id="dow">
                        <div class="empty_state">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                                <path d="M14,17H7V15H14M17,13H7V11H17M17,9H7V7H17M19,3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3Z" fill="currentColor"></path>
                            </svg>
                            СКАЧАТЬ ДОГОВОР
                        </div>
                    </div>
                    <div class="pull-left text-center" id="verif-id">
                        <div class="empty_state">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                                <path d="M14,17H7V15H14M17,13H7V11H17M17,9H7V7H17M19,3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3Z" fill="currentColor"></path>
                            </svg>
                            ЗАГРУЗИТЬ ПОДПИСАННЫЙ ДОГОВОР
                        </div>
                    </div>
                    <div class="pull-right text-center" id="verif-photo" style="display:none">
                        <div class="empty_state">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
                                <path d="M4,5H7L9,3H15L17,5H20A2,2 0 0,1 22,7V19A2,2 0 0,1 20,21H4A2,2 0 0,1 2,19V7A2,2 0 0,1 4,5M16,17V16C16,14.67 13.33,14 12,14C10.67,14 8,14.67 8,16V17H16M12,9A2,2 0 0,0 10,11A2,2 0 0,0 12,13A2,2 0 0,0 14,11A2,2 0 0,0 12,9Z" fill="currentColor"></path>
                            </svg> <?php echo $wo['lang']['personal_pic']; ?>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="terms">
                <input type="checkbox" name="accept_terms" id="accept_terms" onchange="activateButton(this)">
                    <label for="accept_terms">
                        <?php echo $wo['lang']['terms_agreement'] ?> <a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms'); ?>" class="main"><?php echo $wo['lang']['terms_of_use'] ?></a> & <a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy'); ?>" class="main"><?php echo $wo['lang']['privacy_policy'] ?></a>
                    </label>
                    <div class="clear"></div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-main btn-mat btn-mat-raised add_wow_loader"><?php echo $wo['lang']['send']; ?></button>
            </div>

            <input type="file" name="passport" class="hidden" id="select-passport-photo">
                <input type="file" name="photo" class="hidden" id="select-user-photo">
                    <input type="reset" class="hidden" id="reset-verification-request">
                        </form>
                    <?php endif; ?>
                    </div>

                    <!--ДОГОВОР ИП, ЮЛ-->
                    <div id="invoice" style="display: none">
                        <h6>г. Севастополь&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;«__» ________ 2024 г.</h6>
                        <h3 class="entry-title" itemprop="headline">&nbsp;АГЕНТСКИЙ ДОГОВОР №<?php echo $wo['user']['id']; ?> от <?php echo date("m.d.Y"); ?>.</h3>
                        <p id="doc-jl">Индивидуальный предприниматель Тайченачев Максим Денисович, действующий на основании ОГРНИП №322920000017909 (далее – Агент), с одной стороны, и ЮЛ, в лице ФИО(), действующего на основании ДОКУМЕНТ ОСНОВАНИЯ (далее – Принципал), с другой стороны, заключили настоящий договор (далее – Договор) о нижеследующем:</p>
                        <p id="doc-ip">Индивидуальный предприниматель Тайченачев Максим Денисович, действующий на основании ОГРНИП №322920000017909 (далее – Агент), с одной стороны, и Индивидуальный предприниматель <span id="fio_ip"><?php echo ($ver) ? $ver->fio : ''; ?></span>, действующий на основании ОГРНИП <span id="ogrnip_ip"><?php echo ($ver) ? $ver->ogrnip : ''; ?></span> (далее – Принципал), с другой стороны, заключили настоящий договор (далее – Договор) о нижеследующем:</p>
                        <p id="doc-sm" style="display: none">Индивидуальный предприниматель Тайченачев Максим Денисович, действующий на основании ОГРНИП №322920000017909 (далее – Агент), с одной стороны, и <span id="fio_sm"><?php echo ($ver) ? $ver->fio : ''; ?></span>, являющийся плательщиком налога на профессиональный доход (далее – Принципал), с другой стороны, заключили настоящий договор (далее – Договор) о нижеследующем:</p>
                        <h4 id="1-predmet-dogovora">1. Предмет договора</h4>
                        <p>1.1.	Стороны Договора, помимо настоящего Договора, также руководствуются положениями Пользовательского соглашения об оказании услуг по использованию сервиса «Мaxmeet.ru» в части, не противоречащей Договору. С учетом взаимосвязи указанных актов, термины «Принципал» и «Организатор» по тексту Договора являются равнозначными.</p>
                        <p>1.2.	Используемые в договоре термины понимаются в следующих значениях:
                            <ul>
                                <li>- Мероприятие - мастер-класс, презентация, тренинг, семинар, концерт в зале, клубе или на открытой площадке, выставка, шоу, показ мод, спортивное соревнование, экскурсия, а также любое иное событие, цель которых не противоречит действующему законодательству РФ, организованное Принципалом для лиц, являющихся Пользователем Сервиса;</li>
                                <li>- Организатор - лицо, который в рамках настоящего Договора и Пользовательского соглашения об оказании услуг по использованию сервиса «Мaxmeet.ru» использует Сервис для организации Мероприятия, размещения информации о его проведении, предложения оформления его посещения Пользователям Сервиса в случае их заинтересованности и иных соответствующих действий;</li>
                                <li>- Сервис - веб-сайт, расположенный в сети Интернет по адресу https://maxmeet.ru/, а также программы для ЭВМ (в том числе программы для мобильных устройств), на которых указанный сервис предоставляет (будет предоставлять) возможность его использования, созданный и администрируемый Агентом;</li>
                                <li>- Пользователь - обладающее право- и дееспособностью лицо, являющееся зарегистрированным пользователем Сервиса;</li>
                                <li>- Пропуск - форма информационного сообщения, направляемого Сервисом, содержащее название, дату, место проведения и в отдельных случаях стоимость посещения Мероприятия. Получение такого уведомления свидетельствует о приобретении статуса Участника Мероприятия;</li>
                                <li class="beforeClass">- Участник – Пользователь Сервиса, который использовал Сервис для выбора Мероприятия, просмотра информации, размещенной в Сервисе, и приобрел право посещения Мероприятия путем оплаты Пропуска или, если Мероприятие бесплатное, путем регистрации, а также право посещения прямой трансляции в рамках Мероприятия;</li>
                                <li>- Сделка - действия Участника и Принципала по приобретению Пропуска в Сервисе или регистрация на Мероприятие (в случае, если Мероприятие бесплатно для Участника), устанавливающие обязанность Принципала провести Мероприятие и право Участника посетить Мероприятие в указанные в Пропуске дату, время и месте, а также непосредственно проведение Мероприятия и осуществление прямо трансляции в рамках такого Мероприятия. Одна Сделка соотносится только с одним конкретным Мероприятием;</li>
                                <li>- Сервисный сбор – вознаграждение, взимаемое Сервисом с Организатора за предоставление дополнительного функционала и исполнение обязанностей Агента.</li>
                            </ul>
                        </p>
                        <p>1.3.	Принципал в соответствии со статьей 1005 ГК РФ поручает, а Агент обязуется от имени и за счет Принципала совершать Сделки (действия по продаже Пропусков посредством функционала Сервиса), осуществлять техническое обеспечение проведения прямых трансляций Организатора в рамках Мероприятия, принимать исполнение по Сделкам, осуществлять иные действия, необходимые для совершения Сделки и исполнения обязанностей Принципала по ней, принимать от Пользователя денежные средства, поступившие в счет оплаты Пропуска. Продажа Пропусков осуществляется Агентом на условиях, определенных Договором. Денежные средства по Сделкам принимаются на расчетный счет Агента.</p>
                        <p>1.4.	Принципал обязуется уплатить Агенту вознаграждение (сервисный сбор) в порядке и сроки, предусмотренные Договором.</p>
                        <p>1.5.	В рамках исполнения настоящего Договора, на основании требований статьи 51.2. "Основ законодательства Российской Федерации о культуре" (утв. ВС РФ 09.10.1992 № 3612-1), Принципал не имеет права поручать Агенту реализацию билетов, абонементов и экскурсионных путевок на проводимые организациями исполнительских искусств и музеями зрелищные мероприятия (перепродажу таких билетов, абонементов и экскурсионных путевок).</p>
                        <h4 id="2-fin-yslovia">2.	Финансовые условия Договора</h4>
                        <p>2.1.	Вознаграждение Агента (Сервисный сбор) состоит из следующих денежных средств:
                            <ul>
                                <li>- вознаграждение за совершение Агентом обязанностей по настоящему Договору (совершение Сделок, осуществление технического обеспечения проведения трансляций Организатора в рамках Мероприятия и пр.); </li>
                                <li   class="beforeClass">- денежные средства, равные расходам Агента за на оплату комиссий платежных операторов и банков за проведение платежей от Пользователей в случае их наличия. Принципал осознает, что размер комиссий платежных операторов не зависит от Агента, может быть изменен как в большую, так и в меньшую стороны, и не подлежит согласованию с Принципалом или уведомления Принципала.</li>
                            </ul>

                        </p>
                        <p>2.2.	Размер вознаграждения за совершение Агентом обязанностей по настоящему Договору рассчитывается математическим сложением 30% от суммы Сделки (сумма одной Сделки равна общей сумме денежных средств, полученных Агентом за все проданные им Пропуска на одно конкретное Мероприятие) и денежных средств за осуществление Агентом технического обеспечения проведения трансляции Организатора в рамках Мероприятия (данные денежные средства исчисляются по фиксированной цене, предусмотренной пунктом 2.3. настоящего Договора).</p>
                        <p>2.3.	Денежные средства, уплачиваемые за осуществление Агентом технического обеспечения проведения трансляций Оргнизатора в рамках Мероприятия, рассчитываются следующим образом:
                            <ul>
                                <li>- 1 час, отсчет которого начинается с наступления времени, указанного Организатором касаемо конкретного Мероприятия, оплачивается в размере 1000 рублей;</li>
                                <li>- По истечении вышеуказанного часа каждый последующий час оплачивается в размере 250 рублей.</li>
                            </ul>
                        </p>
                        <p>2.4.	Агент по запросу Принципала, но не ранее истечения 7 рабочих дней после даты проведения Мероприятия, перечисляет на его расчетный счет, указанный в настоящем Договоре, денежные средства, полученные в ходе реализации Пропусков в рамках одной Сделки, за вычетом суммы вознаграждения Агента, предусмотренной пунктом 2.1. настоящего Договора.</p>
                        <p>2.5.	Агент вправе приостановить реализацию Пропусков в случае поступления информации, что организуемое Принципалом Мероприятие может нарушать права третьих лиц и/или требования законодательства РФ, и/или требует наличия лицензии или разрешительных документов, и/или нарушает условия пункта 3.1.9. Пользовательского соглашения об оказании услуг по использованию сервиса «Мaxmeet.ru». В таком случае реализация Пропусков Агентом будет восстановлена при условии получения им соответствующих разъяснений о правомерности Мероприятия или необходимых документов от Принципала.</p>
                        <p>2.6.	Принципал перед направлением запроса, предусмотренного пунктом 2.4. настоящего Договора, обязан направить Агенту отчет о проведенном Мероприятии в порядке, предусмотренном пунктом 3.3.4. Пользовательского соглашения об оказании услуг по использованию сервиса «Мaxmeet.ru». В случае отсутствия указанного отчета Агент приостанавливает рассмотрение соответствующего запроса и не перечисляет денежные средства до дня получения Агентом необходимого отчета.</p>
                        <h4 id="3-prava-agenta"   class="beforeClass">3.	Права и обязанности Агента</h4>
                        <p>3.1.	Агент обязуется самостоятельно или с привлечением третьих лиц своевременно и надлежащим образом осуществлять реализацию Пропусков. Информация о проданных Пропусках отображается в дополнительном функционале Организатора в пользовательском профиле Принципала.</p>
                        <p>3.2.	Агент обязуется в случае реализации Пропуска предоставлять Участнику соответствующее уведомление в Сервисе.</p>
                        <p>3.3.	Агент вправе запрашивать, а Принципал обязуется предоставить информацию о предоставляемых Принципалом услугах в рамках Мероприятий.</p>
                        <p>3.4.	Агент вправе блокировать доступ Принципалу к Сервису, в случае, если у него есть подозрения, что неуполномоченные лица получили не санкционированный Принципалом доступ к его профилю. В таком случае Агент уведомляет Принципала о приостановке путем направления информационного сообщения способами связи, содержащимися в реквизитах Принципала в настоящем Договоре.</p>
                        <p>3.5.	Агент вправе проводить модерацию Мероприятий, создаваемых Принципалом.</p>
                        <p>3.6.	Агент вправе удалить Мероприятие в случае, если Принципалом не предоставлены разъяснения о правомерности Мероприятия или необходимые документы, предоставление которых предусмотрено пунктом 2.4. настоящего Договора.</p>
                        <p>3.7.	Агент обязан при поступлении запроса Принципала, предусмотренного пунктом 2.4. настоящего Договора, кроме перечисления денежных средств направить Принципалу агентский отчет, содержащий информацию об исполнении обязанностей по конкретной Сделке, о расчете и величине Сервисного сбора. Стороны договорились, что доказательства расходов, произведенных Агентом за счет Принципала, к вышеуказанному отчету не прикладываются. Отчет считается полученным Принципалом с момента отражения соответствующей информации в дополнительном функционале Организатора в пользовательском профиле Принципала.</p>
                        <h4 id="4-prava-princip">4.	Права и обязанности Принципала</h4>
                        <p>4.1.	Принципал обязуется своевременно и надлежащим образом исполнять свои обязанности, предусмотренные настоящим Договором.</p>
                        <p>4.2.	Принципал обязан самостоятельно уведомить Участников и Агента о факте отмены/замены/переноса Мероприятия.</p>
                        <p>4.3.	Принципал обязан сохранять в конфиденциальности и не разглашать третьим лицам полученную им в ходе Мероприятия информацию, касающуюся персональных данных Участников.</p>
                        <p   class="beforeClass">4.4.	Принципал обязан самостоятельно и надлежащим образом исполнить обязательства перед Участниками по проведению Мероприятия, самостоятельно урегулировать возникающие в этой связи претензии.</p>
                        <p>4.5.	Принципал обязуется нести ответственность за правомерность и легитимность проводимых им Мероприятий, включая, но не ограничиваясь требованиями, предусмотренными Пользовательским соглашением об оказании услуг по использованию сервиса «Мaxmeet.ru».</p>
                        <p>4.6.	Принципал обязуется сообщать Агенту о любых изменениях, способных повлиять на исполнение Сторонами Договора, в частности, об изменениях фамилии, имени или отчества, адреса, банковских реквизитов, применяемой системы налогообложения и др. Принципал осознает, что в противном случае Агент не сможет надлежащим образом и в согласованные сроки выполнить свои обязательства, и в этой связи не может предъявлять Агенту претензии, связанные с этим обстоятельством.</p>
                        <p>4.7.	Принципал направляет запрос, предусмотренный пунктом 2.4. настоящего Договора, в порядке, предусмотренном этим же пунктом, посредством дополнительного функционала Организатора в Сервисе.</p>
                        <h4 id="5-otvetstvennost">5.	Ответственность сторон</h4>
                        <p>5.1.	Агент не несет ответственность по обязательствам Принципала, связанным с предоставлением Участникам услуг, являющихся предметом Сделок, по качеству Мероприятий, а также за отказ Принципала в обслуживании или прекращение обслуживания Участников.</p>
                        <p>5.2.	Агент не несет ответственности за неполучение Принципалом необходимой информации или неполучение ее в оговоренный Договором срок, в связи с техническими проблемами в сети Принципала, а также из-за неполадок в работе Сервиса и/или сети, связанных с действиями третьих лиц, на деятельность которых Агент не может повлиять (организации электроснабжения, хакеры и пр.)</p>
                        <p>5.3.	Стороны освобождаются от ответственности в соответствии с условиями Пользовательского соглашения об оказании услуг по использованию сервиса «Maxmeet.ru» в части, регулирующей обстоятельства непреодолимой силы.</p>
                        <h4 id="6-zakluchenie">6.	Заключительные положения</h4>
                        <p >6.1.	Договор, его заключение, исполнение и расторжение регулируется действующим законодательством РФ. Все вопросы, не урегулированные Договором или урегулированные не полностью, регулируются в соответствии с законодательством РФ</p>
                        <p   class="beforeClass">6.2.	Все возникающие споры, возникающие в связи с условиями настоящего Договора, разрешаются на основании законодательства РФ. Все споры, разногласия и претензии, которые могут возникнуть в связи с исполнением, расторжением или признанием недействительным настоящего Договора, стороны будут стремиться решить путем переговоров. Сторона, у которой возникли претензии и/или разногласия, направляет другой стороне сообщение с указанием возникших претензий и/или разногласий.</p>
                        <p>6.3.	Споры, не разрешенные Сторонами путем переговоров, подлежат рассмотрению в суде общей юрисдикции по местонахождению Агента.</p>
                        <p>6.4.	Стороны договорились, что сведения, являющиеся необходимыми для исполнения обязанностей Сторон и условий Договора, могут быть переданы с помощью телефона, адреса и email, указанных в разделе 7 настоящего Договора, либо посредством функционала Сервиса в случае прямого предусмотрения такого условия в положениях настоящего Договора. Переданные такими способами сведения являются юридически значимыми.</p>
                        <p>6.5.	Стороны обязуются не разглашать информацию об условиях Договора, а также прочую информацию, полученную Сторонами в ходе выполнения своих обязательств по Договору, кроме случаев, если согласие на разглашение информации оформлено в письменном виде и подписано Сторонами.</p>
                        <h4 id="7-rekvizit"   class="beforeClass">7.	Реквизиты сторон</h4>
                        <p>Агент:</p>
                        <ul>
                            <li>Индивидуальный предприниматель Тайченачев Максим Денисович</li>
                            <li>Адрес: Россия, г. Севастополь, ул. Проспект Победы, 62 кв. 44</li>
                            <li>ИНН: 920352645985</li>
                            <li>ОГРНИП: 322920000017909</li>
                            <li>Наименование банка: РНКБ БАНК (ПАО) г. Симферополь</li>
                            <li>БИК банка: 043510607</li>
                            <li>Корр. счет: 30101810335100000607</li>
                            <li>Корр. счет: 30101810335100000607</li>
                            <li>Расчетный счет: 40802810740030001357</li>
                            <li>Телефон: ***</li>
                            <li>Email: ***</li>
                            <li>ПОДПИСЬ_____________________________________________________</li>
                            <li>МП</li>
                        </ul>
                        <p>Принципал:</p>
                        <ul>
                            <li id="doc_fio_li" style="display:none">ФИО: <span id="doc_fio"><?php echo ($ver) ? $ver->fio : ''; ?></span></li>
                            <li id="doc_inn_li" style="display:none">ИНН: <span id="doc_inn"><?php echo ($ver) ? $ver->inn : ''; ?></span></li>
                            <li id="doc_org_li" style="display:none">Наименование: <span id="doc_org"><?php echo ($ver) ? $ver->org : ''; ?></span></li>
                            <li id="doc_ogrn_li" style="display:none">ОГРН: <span id="doc_ogrn"><?php echo ($ver) ? $ver->ogrn : ''; ?></span></li>
                            <li id="doc_ogrnip_li" style="display:none">ОГРНИП: <span id="doc_ogrnip"><?php echo ($ver) ? $ver->ogrnip : ''; ?></span></li>
                            <li id="doc_bank_li">Наименование банка: <span id="doc_bank"><?php echo ($ver) ? $ver->bank : ''; ?></span></li>
                            <li id="doc_bik_li">БИК: <span id="doc_bik"><?php echo ($ver) ? $ver->bik : ''; ?></span></li>
                            <li id="doc_rs_li">Р/С: <span id="doc_rs"><?php echo ($ver) ? $ver->rs : ''; ?></span></li>
                            <li id="doc_kor_li">Кор. счет: <span id="doc_kor"><?php echo ($ver) ? $ver->kor : ''; ?></span></li>
                            <li id="doc_adress_li">Адрес <span id="address_type_doc"></span>: <span id="doc_adress"><?php echo ($ver) ? $ver->address : ''; ?></span></li>
                            <li id="doc_tel_li">Телефон: <span id="doc_tel"><?php echo ($ver) ? $ver->tel : ''; ?></span></li>
                            <li id="doc_email_li">Почта: <span id="doc_email"><?php echo ($ver) ? $ver->email : ''; ?></span></li>
                            <li>ПОДПИСЬ_____________________________________________________</li>
                            <li>МП</li>
                        </ul>

                    </div>
                    <!--ЮЛ-->


                    <script src="<?php echo $wo['config']['theme_url']; ?>/javascript/autosize.min.js"></script>
                    <script>
                                        var validator_1 = $(".setting-verification-form").validate({
                                            rules: {
                                                "inn": {
                                                    required: true,
                                                    minlength: 10,
                                                },
                                                "bank": {
                                                    required: true,
                                                    minlength: 3,
                                                },
                                                "bik": {
                                                    required: true,
                                                    minlength: 9,
                                                },
                                                "rs": {
                                                    required: true,
                                                    minlength: 10,
                                                },
                                                "kor": {
                                                    required: true,
                                                    minlength: 10,
                                                },
                                                "adress": {
                                                    required: true,
                                                },
                                                "tel": {
                                                    required: true,
                                                },
                                                "email": {
                                                    required: true,
                                                    email: true,
                                                },
                                            },
                                            messages: {
                                                "inn": {
                                                    required: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* поле не заполнено</span></div>",
                                                    minlength: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* миниум 10 символа</span></div>",
                                                },
                                                "bank": {
                                                    required: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* поле не заполнено</span></div>",
                                                    minlength: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* миниум 3 символа</span></div>",
                                                },
                                                "bik": {
                                                    required: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* поле не заполнено</span></div>",
                                                    minlength: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* миниум 9 символов</span></div>",
                                                },
                                                "rs": {
                                                    required: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* поле не заполнено</span></div>",
                                                    minlength: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* миниум 10 символов</span></div>",
                                                },
                                                "kor": {
                                                    required: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* поле не заполнено</span></div>",
                                                    minlength: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* миниум 10 символов</span></div>",
                                                },
                                                "adress": {
                                                    required: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* поле не заполнено</span></div>",
                                                },
                                                "tel": {
                                                    required: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* поле не заполнено</span></div>",
                                                },
                                                "email": {
                                                    required: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* поле не заполнено</span></div>",
                                                    email: "<div style='background-color:#e86477; border-radius:5px;'><span style='padding: 2px'>* введите e-mail</span></div>",
                                                },
                                            },
                                        });

                                        window.onload = function () {
                                            document.getElementById("dow")
                                                    .addEventListener("click", () => {
                                                        $('#invoice').css('display', 'block');

                                                        const invoice = this.document.getElementById("invoice");
                                                        var opt = {
                                                            margin: 1,
                                                            filename: 'myfile.pdf',
                                                            image: {
                                                                type: 'jpeg',
                                                                quality: 0.98
                                                            },
                                                            html2canvas: {
                                                                scale: 2
                                                            },
                                                            jsPDF: {
                                                                unit: 'in',
                                                                format: 'letter',
                                                                orientation: 'portrait'
                                                            },
                                                            pagebreak: {before: '.beforeClass'}
                                                        };
                                                        html2pdf().from(invoice).set(opt).save();

                                                        setTimeout(() => {
                                                            $('#invoice').css('display', 'none');
                                                        }, 1000);
                                                    });
                                        }
                    </script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
                    <script>
                                        jQuery(document).ready(function ($) {

                                            (function () {
<?php if ($ver && $ver->type_ver == '0') : ?>
                                                    $('#typeform-0').css('display', 'block');
                                                    $('#all_fields').css('display', 'block');
                                                    $('#doc-jl').css('display', 'none');
                                                    $('#doc-ip').css('display', 'block');
                                                    $('#doc_ogrnip_li').css('display', 'block');
                                                    $('.ogrn_fields').css('display', 'inline-grid');
                                                    $('#address_type').text('(регистрации)');
                                                    $('#address_type_doc').text('(регистрации)');
<?php elseif ($ver && $ver->type_ver == '1') : ?>
                                                    $('#typeform-1').css('display', 'block');
                                                    $('#all_fields').css('display', 'block');
                                                    $('#typeform-0').css('display', 'none');
                                                    $('#doc-jl').css('display', 'block');
                                                    $('#doc-ip').css('display', 'none');
                                                    $('#doc_ogrnip_li').css('display', 'none');
                                                    $('.ogrn_fields').css('display', 'none');
                                                    $('#address_type').text('(организации)');
                                                    $('#address_type_doc').text('(организации)');
<?php elseif ($ver && $ver->type_ver == '2') : ?>
                                                    $('#typeform-0').css('display', 'block');
                                                    $('#all_fields').css('display', 'block');
                                                    $('#doc-jl').css('display', 'none');
                                                    $('#doc-ip').css('display', 'none');
                                                    $('#doc-sm').css('display', 'block');
                                                    $('#doc_ogrnip_li').css('display', 'none');
                                                    $('.ogrn_fields').css('display', 'none');
                                                    $('#address_type').text('(регистрации)');
                                                    $('#address_type_doc').text('(регистрации)');
<?php endif; ?>
                                            })();

                                            $('input[type=radio][name=type_ver]').change(function () {
                                                $("#doc_email").text($('#email').val());
                                                if (this.value == '0') {
                                                    $('#typeform-0').css('display', 'block');
                                                    $('#all_fields').css('display', 'block');
                                                    $('#typeform-1').css('display', 'none');

                                                    $('#doc_fio_li').css('display', 'block');
                                                    $('#doc_inn_li').css('display', 'block');
                                                    $('#doc-ip').css('display', 'block');

                                                    $('#doc_org_li').css('display', 'none');
                                                    $('#doc_ogrn_li').css('display', 'none');
                                                    $('#doc-jl').css('display', 'none');
                                                    $('#doc_ogrnip_li').css('display', 'block');
                                                    $('.ogrn_fields').css('display', 'inline-grid');
                                                    $('#address_type').text('(регистрации)');
                                                    $('#address_type_doc').text('(регистрации)');
                                                } else if (this.value == '1') {
                                                    $('#typeform-1').css('display', 'block');
                                                    $('#all_fields').css('display', 'block');
                                                    $('#typeform-0').css('display', 'none');

                                                    $('#doc_fio_li').css('display', 'none');
                                                    $('#doc_inn_li').css('display', 'none');
                                                    $('#doc-ip').css('display', 'none');

                                                    $('#doc_org_li').css('display', 'block');
                                                    $('#doc_ogrn_li').css('display', 'block');
                                                    $('#doc-jl').css('display', 'block');
                                                    $('#doc_ogrnip_li').css('display', 'none');
                                                    $('#address_type').text('(организации)');
                                                    $('#address_type_doc').text('(организации)');
                                                } else if (this.value == '2') {
                                                    console.log(1111);
                                                    $('#typeform-0').css('display', 'block');
                                                    $('#all_fields').css('display', 'block');
                                                    $('#typeform-1').css('display', 'none');

                                                    $('#doc_fio_li').css('display', 'block');
                                                    $('#doc_inn_li').css('display', 'block');
                                                    $('#doc-ip').css('display', 'none');
                                                    $('#doc-sm').css('display', 'block');

                                                    $('#doc_org_li').css('display', 'none');
                                                    $('#doc_ogrn_li').css('display', 'none');
                                                    $('#doc_ogrnip_li').css('display', 'none');
                                                    $('.ogrn_fields').css('display', 'none');
                                                    $('#doc-jl').css('display', 'none');
                                                    $('#address_type').text('(регистрации)');
                                                    $('#address_type_doc').text('(регистрации)');
                                                }
                                            });

                                            //DOC
                                            $("#fio").on("input", function () {
                                                $("#doc_fio").text($('#fio').val());
                                                $("#fio_ip").text($('#fio').val());
                                                $("#fio_sm").text($('#fio').val());


                                            });

                                            $("#inn").on("input", function () {
                                                $("#doc_inn").text($('#inn').val());


                                            });

                                            $("#org").on("input", function () {
                                                $("#doc_org").text($('#org').val());
                                            });

                                            $("#ogrn").on("input", function () {
                                                $("#doc_ogrn").text($('#ogrn').val());
                                                $("#ogrn_ip").text($('#ogrn').val());
                                            });

                                            $("#ogrnip").on("input", function () {
                                                $("#doc_ogrnip").text($('#ogrnip').val());
                                                $("#ogrnip_ip").text($('#ogrnip').val());
                                            });

                                            $("#bank").on("input", function () {
                                                $("#doc_bank").text($('#bank').val());
                                            });

                                            $("#bik").on("input", function () {
                                                $("#doc_bik").text($('#bik').val());
                                            });

                                            $("#rs").on("input", function () {
                                                $("#doc_rs").text($('#rs').val());
                                            });

                                            $("#kor").on("input", function () {
                                                $("#doc_kor").text($('#kor').val());
                                            });

                                            $("#adress").on("input", function () {
                                                $("#doc_adress").text($('#adress').val());
                                            });

                                            $("#tel").on("input", function () {
                                                $("#doc_tel").text($('#tel').val());
                                            });

                                            $("#email").on("input", function () {
                                                $("#doc_email").text($('#email').val());
                                            });
                                            //END DOC


                                            $("#text").autogrow({
                                                vertical: true,
                                                horizontal: false
                                            });

                                            $("#verif-id").click(function (event) {
                                                $("#select-passport-photo").trigger('click');
                                            });

                                            $("#verif-photo").click(function (event) {
                                                $("#select-user-photo").trigger('click');
                                            });

                                            $("#select-passport-photo").change(function (event) {
                                                if (ext(this.files[0].name) == 'jpeg' || ext(this.files[0].name) == 'jpg' || ext(this.files[0].name) == 'png' || ext(this.files[0].name) == 'webp') {

                                                    return $("#verif-id").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture' class='responsive-img'>");
                                                }
                                                $("#verif-id").html("<p class='responsive-img btn btn-main btn-mat' style='margin:0;font-family: Poppins'>" + this.files[0].name + "</p>");

                                            });

                                            $("#select-user-photo").change(function (event) {
                                                $("#verif-photo").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture' class='responsive-img'>")
                                            });

                                            function ext(name) {
                                                var m = name.match(/\.([^.]+)$/)
                                                return m && m[1];
                                            }


                                            $(".setting-verification-form").ajaxForm({
                                                url: Wo_Ajax_Requests_File() + '?f=verificate-user',
                                                beforeSend: function () {
                                                    $('.wo_settings_page').find('.add_wow_loader').addClass('btn-loading');
                                                },
                                                success: function (data) {
                                                    scrollToTop();
                                                    if (data['status'] == 200) {
                                                        console.log(data['url']);
                                                        $("#verificate-user-alert").html('<div class="alert alert-success">' + data['message'] + '</div>');
                                                        window.location = data['url'];
                                                    } else {
                                                        $("#verificate-user-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
                                                    }
                                                    $('.wo_settings_page').find('.add_wow_loader').removeClass('btn-loading');
                                                }
                                            });
                                        });
                    </script>